# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

github: [metadata]

# Site settings
title: 룻애져의 글뭉치
author:
  name: LUSazure
  email: lusazure@gmail.com
repository: LUSazure/lusazure.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lusazure
github_username:  lusazure

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
# (I'm not used to this framework(?)'s organization thingy, yet I had to add some settings.)
permalink: /:categories/:path/:title

collections_dir: collections

collections:
  posts: 
    output: true
    permalink: /:categories/:title

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/